// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	core "github.com/xkilldash9x/scalpel-cli/internal/analysis/core"
)

// MockHeadersAnalyzer is an autogenerated mock type for the AnalyzerInterface type
type MockHeadersAnalyzer struct {
	mock.Mock
}

// Analyze provides a mock function with given fields: ctx, analysisCtx
func (_m *MockHeadersAnalyzer) Analyze(ctx context.Context, analysisCtx *core.AnalysisContext) error {
	ret := _m.Called(ctx, analysisCtx)

	if len(ret) == 0 {
		panic("no return value specified for Analyze")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.AnalysisContext) error); ok {
		r0 = rf(ctx, analysisCtx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockHeadersAnalyzer creates a new instance of MockHeadersAnalyzer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHeadersAnalyzer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHeadersAnalyzer {
	mock := &MockHeadersAnalyzer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
