// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	schemas "github.com/xkilldash9x/scalpel-cli/api/schemas"
)

// BrowserInteractor is an autogenerated mock type for the BrowserInteractor type
type BrowserInteractor struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *BrowserInteractor) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetArtifacts provides a mock function with given fields: ctx
func (_m *BrowserInteractor) GetArtifacts(ctx context.Context) (*schemas.Artifacts, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifacts")
	}

	var r0 *schemas.Artifacts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*schemas.Artifacts, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *schemas.Artifacts); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schemas.Artifacts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Navigate provides a mock function with given fields: ctx, url, persona
func (_m *BrowserInteractor) Navigate(ctx context.Context, url string, persona *schemas.Persona) error {
	ret := _m.Called(ctx, url, persona)

	if len(ret) == 0 {
		panic("no return value specified for Navigate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *schemas.Persona) error); ok {
		r0 = rf(ctx, url, persona)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBrowserInteractor creates a new instance of BrowserInteractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrowserInteractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrowserInteractor {
	mock := &BrowserInteractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
