// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	schemas "github.com/xkilldash9x/scalpel-cli/api/schemas"
)

// BrowserManager is an autogenerated mock type for the BrowserManager type
type BrowserManager struct {
	mock.Mock
}

// GetBrowser provides a mock function with no fields
func (_m *BrowserManager) GetBrowser() (schemas.BrowserInteractor, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBrowser")
	}

	var r0 schemas.BrowserInteractor
	var r1 error
	if rf, ok := ret.Get(0).(func() (schemas.BrowserInteractor, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() schemas.BrowserInteractor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(schemas.BrowserInteractor)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReleaseBrowser provides a mock function with given fields: browser
func (_m *BrowserManager) ReleaseBrowser(browser schemas.BrowserInteractor) {
	_m.Called(browser)
}

// NewBrowserManager creates a new instance of BrowserManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrowserManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrowserManager {
	mock := &BrowserManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
