// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	schemas "github.com/xkilldash9x/scalpel-cli/api/schemas"
)

// KnowledgeGraphClient is an autogenerated mock type for the KnowledgeGraphClient type
type KnowledgeGraphClient struct {
	mock.Mock
}

// BulkUpdate provides a mock function with given fields: ctx, updates
func (_m *KnowledgeGraphClient) BulkUpdate(ctx context.Context, updates schemas.KnowledgeGraphUpdate) error {
	ret := _m.Called(ctx, updates)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, schemas.KnowledgeGraphUpdate) error); ok {
		r0 = rf(ctx, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKnowledgeGraphClient creates a new instance of KnowledgeGraphClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKnowledgeGraphClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *KnowledgeGraphClient {
	mock := &KnowledgeGraphClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
