// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	schemas "github.com/xkilldash9x/scalpel-cli/api/schemas"
)

// OASTProvider is an autogenerated mock type for the OASTProvider type
type OASTProvider struct {
	mock.Mock
}

// GetInteractions provides a mock function with given fields: ctx, payload
func (_m *OASTProvider) GetInteractions(ctx context.Context, payload string) ([]schemas.OASTInteraction, error) {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for GetInteractions")
	}

	var r0 []schemas.OASTInteraction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]schemas.OASTInteraction, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []schemas.OASTInteraction); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]schemas.OASTInteraction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPayload provides a mock function with no fields
func (_m *OASTProvider) NewPayload() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewPayload")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewOASTProvider creates a new instance of OASTProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOASTProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *OASTProvider {
	mock := &OASTProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
