// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"

	schemas "github.com/xkilldash9x/scalpel-cli/api/schemas"

	time "time"
)

// SessionContext is an autogenerated mock type for the SessionContext type
type SessionContext struct {
	mock.Mock
}

// AddFinding provides a mock function with given fields: ctx, finding
func (_m *SessionContext) AddFinding(ctx context.Context, finding schemas.Finding) error {
	ret := _m.Called(ctx, finding)

	if len(ret) == 0 {
		panic("no return value specified for AddFinding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, schemas.Finding) error); ok {
		r0 = rf(ctx, finding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Click provides a mock function with given fields: ctx, selector
func (_m *SessionContext) Click(ctx context.Context, selector string) error {
	ret := _m.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for Click")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, selector)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with given fields: ctx
func (_m *SessionContext) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CollectArtifacts provides a mock function with given fields: ctx
func (_m *SessionContext) CollectArtifacts(ctx context.Context) (*schemas.Artifacts, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CollectArtifacts")
	}

	var r0 *schemas.Artifacts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*schemas.Artifacts, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *schemas.Artifacts); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schemas.Artifacts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DispatchMouseEvent provides a mock function with given fields: ctx, data
func (_m *SessionContext) DispatchMouseEvent(ctx context.Context, data schemas.MouseEventData) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for DispatchMouseEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, schemas.MouseEventData) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DispatchStructuredKey provides a mock function with given fields: ctx, data
func (_m *SessionContext) DispatchStructuredKey(ctx context.Context, data schemas.KeyEventData) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for DispatchStructuredKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, schemas.KeyEventData) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecuteScript provides a mock function with given fields: ctx, script, args
func (_m *SessionContext) ExecuteScript(ctx context.Context, script string, args []interface{}) (json.RawMessage, error) {
	ret := _m.Called(ctx, script, args)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteScript")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []interface{}) (json.RawMessage, error)); ok {
		return rf(ctx, script, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []interface{}) json.RawMessage); ok {
		r0 = rf(ctx, script, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []interface{}) error); ok {
		r1 = rf(ctx, script, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExposeFunction provides a mock function with given fields: ctx, name, function
func (_m *SessionContext) ExposeFunction(ctx context.Context, name string, function interface{}) error {
	ret := _m.Called(ctx, name, function)

	if len(ret) == 0 {
		panic("no return value specified for ExposeFunction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, name, function)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetElementGeometry provides a mock function with given fields: ctx, selector
func (_m *SessionContext) GetElementGeometry(ctx context.Context, selector string) (*schemas.ElementGeometry, error) {
	ret := _m.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for GetElementGeometry")
	}

	var r0 *schemas.ElementGeometry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*schemas.ElementGeometry, error)); ok {
		return rf(ctx, selector)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *schemas.ElementGeometry); ok {
		r0 = rf(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schemas.ElementGeometry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ID provides a mock function with no fields
func (_m *SessionContext) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// InjectScriptPersistently provides a mock function with given fields: ctx, script
func (_m *SessionContext) InjectScriptPersistently(ctx context.Context, script string) error {
	ret := _m.Called(ctx, script)

	if len(ret) == 0 {
		panic("no return value specified for InjectScriptPersistently")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, script)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Interact provides a mock function with given fields: ctx, config
func (_m *SessionContext) Interact(ctx context.Context, config schemas.InteractionConfig) error {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for Interact")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, schemas.InteractionConfig) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Navigate provides a mock function with given fields: ctx, url
func (_m *SessionContext) Navigate(ctx context.Context, url string) error {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Navigate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ScrollPage provides a mock function with given fields: ctx, direction
func (_m *SessionContext) ScrollPage(ctx context.Context, direction string) error {
	ret := _m.Called(ctx, direction)

	if len(ret) == 0 {
		panic("no return value specified for ScrollPage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, direction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendKeys provides a mock function with given fields: ctx, keys
func (_m *SessionContext) SendKeys(ctx context.Context, keys string) error {
	ret := _m.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for SendKeys")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, keys)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Sleep provides a mock function with given fields: ctx, d
func (_m *SessionContext) Sleep(ctx context.Context, d time.Duration) error {
	ret := _m.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for Sleep")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) error); ok {
		r0 = rf(ctx, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Submit provides a mock function with given fields: ctx, selector
func (_m *SessionContext) Submit(ctx context.Context, selector string) error {
	ret := _m.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, selector)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Type provides a mock function with given fields: ctx, selector, text
func (_m *SessionContext) Type(ctx context.Context, selector string, text string) error {
	ret := _m.Called(ctx, selector, text)

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, selector, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WaitForAsync provides a mock function with given fields: ctx, milliseconds
func (_m *SessionContext) WaitForAsync(ctx context.Context, milliseconds int) error {
	ret := _m.Called(ctx, milliseconds)

	if len(ret) == 0 {
		panic("no return value specified for WaitForAsync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, milliseconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSessionContext creates a new instance of SessionContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionContext {
	mock := &SessionContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
