// package taint defines the core data structures, constants, and interfaces
// used throughout the IAST analysis system.
package taint

import (
	"net/url"
	"time"

	"github.com/xkilldash9x/scalpel-cli/api/schemas"
)

// Constants defining the names of Go functions exposed to the browser's
// JavaScript environment. These create the callback bridge from the JS shim
// back to the Go analyzer.
const (
	JSCallbackSinkEvent      = "__scalpel_sink_event"
	JSCallbackExecutionProof = "__scalpel_execution_proof"
	JSCallbackShimError      = "__scalpel_shim_error"
)

// Event is a marker interface for all types of events that can be sent to the
// correlation engine. This allows various event structs (SinkEvent,
// ExecutionProofEvent, etc.) to be sent over the same channel.
type Event interface {
	isEvent()
}

// SanitizationLevel categorizes the degree to which a payload has been altered
// by the application before it reaches a sink.
type SanitizationLevel int

const (
	// SanitizationNone indicates the payload reached the sink completely unchanged.
	SanitizationNone SanitizationLevel = iota
	// SanitizationPartial indicates that the core canary was found, but the
	// surrounding payload was modified (e.g., HTML tags stripped or quotes escaped).
	SanitizationPartial
)

// ProbeDefinition defines the blueprint for a single attack payload, including
// its type, the payload template, and a description.
type ProbeDefinition struct {
	Type        schemas.ProbeType `json:"type" yaml:"type"`
	Payload     string            `json:"payload" yaml:"payload"`
	Context     string            `json:"context" yaml:"context"`
	Description string            `json:"description" yaml:"description"`
}

// ActiveProbe represents an instance of a ProbeDefinition that has been injected
// into the target. It includes the unique canary used for tracking and metadata
// about its injection point (source).
type ActiveProbe struct {
	Type      schemas.ProbeType
	Key       string // The name/key used for injection (e.g., URL parameter name).
	Value     string // The full payload after template substitution.
	Canary    string // The unique identifier for this probe instance.
	Source    schemas.TaintSource
	CreatedAt time.Time
}

// SinkEvent is generated by the JavaScript shim when a value containing a canary
// is passed to an instrumented sink (e.g., `element.innerHTML = taintedValue`).
type SinkEvent struct {
	Type       schemas.TaintSink `json:"type"`       // The type of sink that was triggered.
	Value      string            `json:"value"`      // The tainted value observed at the sink.
	Detail     string            `json:"detail"`     // Additional context, like the property name.
	StackTrace string            `json:"stack"`      // The JavaScript stack trace.
}

func (SinkEvent) isEvent() {}

// ExecutionProofEvent is generated by the JavaScript shim when a payload's
// canary is executed as code (e.g., via `eval` or an event handler), providing
// definitive proof of a vulnerability like XSS.
type ExecutionProofEvent struct {
	Canary     string `json:"canary"`
	StackTrace string `json:"stack"`
}

func (ExecutionProofEvent) isEvent() {}

// ShimErrorEvent is used to report internal errors from the JavaScript
// instrumentation shim back to the Go backend for debugging purposes.
type ShimErrorEvent struct {
	Error      string `json:"error"`
	Location   string `json:"location"`
	StackTrace string `json:"stack"`
}

func (ShimErrorEvent) isEvent() {}

// OASTInteraction represents an out-of-band interaction (e.g., an HTTP or DNS
// request) received by the OAST server. It implements the Event interface so it
// can be processed by the correlation engine.
type OASTInteraction struct {
	Canary          string
	Protocol        string
	SourceIP        string
	InteractionTime time.Time
	RawRequest      string
}

func (OASTInteraction) isEvent() {}

// CorrelatedFinding is the final, structured output of the taint analysis
// engine. It represents a confirmed or potential vulnerability, linking a taint
// source (Probe) to a sink and including all relevant evidence.
type CorrelatedFinding struct {
	TaskID            string
	TargetURL         string
	Sink              schemas.TaintSink
	Origin            schemas.TaintSource
	Value             string // The value observed at the sink.
	Canary            string
	Probe             ActiveProbe
	Detail            string
	IsConfirmed       bool // True if confirmed by execution proof or OAST.
	SanitizationLevel SanitizationLevel
	StackTrace        string
	OASTDetails       *OASTInteraction // Details if confirmed via OAST.
}

// OASTProvider is an alias for the canonical `schemas.OASTProvider` interface,
// used here to decouple the analyzer from the API schema package if needed.
type OASTProvider schemas.OASTProvider

// SessionContext is an alias for the canonical `schemas.SessionContext` interface.
type SessionContext schemas.SessionContext

// ResultsReporter defines a simple, thread-safe interface for reporting
// correlated findings back to the main analysis context.
type ResultsReporter interface {
	Report(finding CorrelatedFinding)
}

// SinkDefinition provides the blueprint for instrumenting a single JavaScript
// sink. It specifies the full property path, its sink type, and whether it's a
// function call or a property setter.
type SinkDefinition struct {
	Name        string            `json:"Name" yaml:"name"`     // Full property path (e.g., "Element.prototype.innerHTML").
	Type        schemas.TaintSink `json:"Type" yaml:"type"`     // The canonical sink type.
	Setter      bool              `json:"Setter" yaml:"setter"` // True if this is a property setter.
	ArgIndex    int               `json:"ArgIndex" yaml:"arg_index"` // The argument index to inspect for taint (for function calls).
	ConditionID string            `json:"ConditionID,omitempty" yaml:"condition_id,omitempty"` // An optional ID for a JS-side pre-condition.
}

// Config encapsulates all settings and parameters for a single taint analysis
// task, from the target and probes to performance tuning and timeouts.
type Config struct {
	TaskID      string                  `json:"task_id" yaml:"task_id"`
	Target      *url.URL                `json:"target" yaml:"target"`
	Probes      []ProbeDefinition       `json:"probes" yaml:"probes"`
	Sinks       []SinkDefinition        `json:"sinks" yaml:"sinks"`
	Interaction schemas.InteractionConfig `json:"interaction" yaml:"interaction"`

	// AnalysisTimeout is the total maximum duration for the entire analysis task.
	AnalysisTimeout time.Duration `json:"analysis_timeout" yaml:"analysis_timeout"`

	// -- Performance & Concurrency Tuning --
	CorrelationWorkers      int           `json:"correlation_workers" yaml:"correlation_workers"`
	EventChannelBuffer      int           `json:"event_channel_buffer" yaml:"event_channel_buffer"`
	FinalizationGracePeriod time.Duration `json:"finalization_grace_period" yaml:"finalization_grace_period"`
	ProbeExpirationDuration time.Duration `json:"probe_expiration_duration" yaml:"probe_expiration_duration"`
	CleanupInterval         time.Duration `json:"cleanup_interval" yaml:"cleanup_interval"`
	OASTPollingInterval     time.Duration `json:"oast_polling_interval" yaml:"oast_polling_interval"`
}