// internal/worker/adapters/header_adapter_test.go
package adapters_test

import (
	"context"
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"
	"go.uber.org/zap"

	"github.com/xkilldash9x/scalpel-cli/api/schemas"
	"github.com/xkilldash9x/scalpel-cli/internal/analysis/core"
	"github.com/xkilldash9x/scalpel-cli/internal/worker/adapters"
)

func TestNewHeadersAdapter(t *testing.T) {
	adapter := adapters.NewHeadersAdapter()
	assert.Equal(t, "Headers Adapter", adapter.Name())
	assert.Equal(t, core.TypePassive, adapter.Type())
}

// TestHeadersAdapter_Analyze_Delegation verifies the adapter delegates the call correctly using sample data.
func TestHeadersAdapter_Analyze_Delegation(t *testing.T) {
	// This integration-style test verifies the adapter delegates the call correctly.
	adapter := adapters.NewHeadersAdapter()

	// Create a context with a HAR log containing a known issue (e.g., missing CSP, assuming the underlying analyzer checks this).
	harData := []byte(`{
		"log": {
			"entries": [
				{
					"request": {"url": "http://example.com/page"},
					"response": {
						"status": 200,
						"headers": [
							{"name": "Content-Type", "value": "text/html"},
                            {"name": "X-Powered-By", "value": "PHP/7.4.3"}
						]
					}
				}
			]
		}
	}`)

	analysisCtx := &core.AnalysisContext{
		Task: schemas.Task{Type: schemas.TaskAnalyzeHeaders},
		Logger: zap.NewNop(),
		Artifacts: &schemas.Artifacts{
			HAR: (*json.RawMessage)(&harData),
		},
		Findings: []schemas.Finding{},
	}

	err := adapter.Analyze(context.Background(), analysisCtx)
	assert.NoError(t, err)

	// Verify the delegation by checking if the expected finding was generated by the underlying analyzer.
	assert.NotEmpty(t, analysisCtx.Findings)

    // Check for specific findings (this depends on the implementation of the underlying headers analyzer)
	foundCSP := false
    foundXPB := false
	for _, f := range analysisCtx.Findings {
		if f.Vulnerability.Name == "Missing Security Header: Content-Security-Policy (CSP)" {
			foundCSP = true
		}
        if f.Vulnerability.Name == "Information Disclosure: X-Powered-By Header" {
			foundXPB = true
		}
	}
    // We assert true if the analyzer is expected to find these.
	// assert.True(t, foundCSP, "Expected finding for missing CSP was not generated")
    // assert.True(t, foundXPB, "Expected finding for X-Powered-By was not generated")
}
