// pkg/humanoid/config.go
package humanoid

import (
	"math"
	"math/rand"
)

// Config holds the parameters defining the behavior of the simulation.
type Config struct {
	Rng *rand.Rand

	// -- Distribution Parameters (Define the Persona archetype) --

	// Fitts's Law Parameters (Movement Time = A + B * ID)
	FittsAMean, FittsAStdDev float64
	FittsBMean, FittsBStdDev float64

	// Motor Control Dynamics (Damped Harmonic Oscillator Model)
	OmegaMean, OmegaStdDev float64 // Responsiveness/speed (Natural Frequency)
	ZetaMean, ZetaStdDev   float64 // Damping ratio (Note: Current simulation assumes Zeta=1.0)

	// Noise and Tremor
	GaussianStrengthMean, GaussianStrengthStdDev float64
	PerlinAmplitudeMean, PerlinAmplitudeStdDev   float64
	ClickNoiseMean, ClickNoiseStdDev             float64 // Max pixel deviation during a click event

	// Typing Behavior
	TypoRateMean, TypoRateStdDev   float64
	KeyHoldMeanMs, KeyHoldStdDevMs float64 // Key hold duration (Dwell time)

	// -- Instance Parameters (Generated by FinalizeSessionPersona, used as base for dynamic config) --

	FittsA, FittsB             float64
	Omega, Zeta                float64
	GaussianStrength           float64
	PerlinAmplitude            float64
	ClickNoise                 float64
	TypoRate                   float64
	KeyHoldMean, KeyHoldStdDev float64

	// -- Clicking Behavior --
	ClickHoldMinMs int `json:"click_hold_min_ms" yaml:"click_hold_min_ms"` // Minimum click duration.
	ClickHoldMaxMs int `json:"click_hold_max_ms" yaml:"click_hold_max_ms"` // Maximum click duration.

	// -- Shared Parameters --

	// Conditional Typo Probabilities (Proportions)
	TypoNeighborRate  float64
	TypoTransposeRate float64
	TypoOmissionRate  float64
	TypoInsertionRate float64

	// Scrolling Behavior
	ScrollReadDensityFactor     float64
	ScrollMouseWheelProbability float64
	ScrollRegressionProbability float64
	ScrollOvershootProbability  float64

	// Fatigue Modeling
	FatigueIncreaseRate float64 // Rate fatigue accumulates per action intensity unit
	FatigueRecoveryRate float64 // Rate fatigue recovers per second of inactivity

	// Movement Refinement
	MicroCorrectionThreshold float64 // Note: Not strictly used in the current CDS model implementation
}

// Persona represents a predefined set of configurations.
type Persona string

const (
	PersonaDefault      Persona = "Default"
	PersonaFastSkilled  Persona = "FastSkilled"
	PersonaSlowCautious Persona = "SlowCautious"
)

// GetConfigForPersona returns the configuration archetype for a specific persona.
func GetConfigForPersona(persona Persona) Config {
	var c Config
	switch persona {
	case PersonaFastSkilled:
		c = DefaultConfig()
		// Example settings (omitted for brevity)

	case PersonaSlowCautious:
		c = DefaultConfig()
		// Example settings

	case PersonaDefault:
		fallthrough
	default:
		c = DefaultConfig()
	}
	c.NormalizeTypoRates()
	return c
}

// DefaultConfig returns a configuration representing an average, skilled adult user archetype.
func DefaultConfig() Config {
	c := Config{
		Rng: nil,

		// Fitts's Law
		FittsAMean: 100.0, FittsAStdDev: 15.0,
		FittsBMean: 120.0, FittsBStdDev: 20.0,

		// Dynamics
		OmegaMean: 28.0, OmegaStdDev: 4.0,
		ZetaMean: 1.0, ZetaStdDev: 0.1, // Critically damped by default

		// Noise
		GaussianStrengthMean: 0.5, GaussianStrengthStdDev: 0.1,
		PerlinAmplitudeMean: 2.5, PerlinAmplitudeStdDev: 0.5,
		ClickNoiseMean: 2.0, ClickNoiseStdDev: 0.5,

		// Typing
		TypoRateMean:    0.04, TypoRateStdDev: 0.01,
		KeyHoldMeanMs: 55.0, KeyHoldStdDevMs: 15.0,

		// Clicking
		ClickHoldMinMs: 50, ClickHoldMaxMs: 120,

		// Typo distributions
		TypoNeighborRate:  0.40,
		TypoTransposeRate: 0.25,
		TypoOmissionRate:  0.20,
		TypoInsertionRate: 0.15,

		// Scrolling
		ScrollReadDensityFactor:     0.5,
		ScrollMouseWheelProbability: 0.70,
		ScrollRegressionProbability: 0.10,
		ScrollOvershootProbability:  0.25,

		// Fatigue
		FatigueIncreaseRate: 0.005,
		FatigueRecoveryRate: 0.01, // 1% per second

		MicroCorrectionThreshold: 50.0,
	}
	c.NormalizeTypoRates()
	return c
}

// Helper for Gaussian sampling
func sampleGaussian(rng *rand.Rand, mean, stdDev float64) float64 {
	if rng == nil {
		return mean
	}
	return mean + rng.NormFloat64()*stdDev
}

// FinalizeSessionPersona generates the fixed instance parameters for a session.
func (c *Config) FinalizeSessionPersona(rng *rand.Rand) {
	c.Rng = rng

	c.FittsA = sampleGaussian(rng, c.FittsAMean, c.FittsAStdDev)
	c.FittsB = sampleGaussian(rng, c.FittsBMean, c.FittsBStdDev)

	c.Omega = sampleGaussian(rng, c.OmegaMean, c.OmegaStdDev)
	c.Zeta = sampleGaussian(rng, c.ZetaMean, c.ZetaStdDev)

	c.GaussianStrength = sampleGaussian(rng, c.GaussianStrengthMean, c.GaussianStrengthStdDev)
	c.PerlinAmplitude = sampleGaussian(rng, c.PerlinAmplitudeMean, c.PerlinAmplitudeStdDev)

	c.ClickNoise = sampleGaussian(rng, c.ClickNoiseMean, c.ClickNoiseStdDev)

	c.TypoRate = sampleGaussian(rng, c.TypoRateMean, c.TypoRateStdDev)
	c.KeyHoldMean = sampleGaussian(rng, c.KeyHoldMeanMs, c.KeyHoldStdDevMs)
	c.KeyHoldStdDev = c.KeyHoldStdDevMs

	// Ensure parameters are within reasonable bounds
	c.Omega = math.Max(5.0, c.Omega)
	c.ClickNoise = math.Max(0.0, c.ClickNoise)
	c.TypoRate = math.Max(0.0, math.Min(0.25, c.TypoRate))
	c.KeyHoldMean = math.Max(20.0, c.KeyHoldMean)

	// Ensure click hold range is valid to prevent issues later (e.g. rand.Intn(0))
	if c.ClickHoldMaxMs <= c.ClickHoldMinMs {
		c.ClickHoldMaxMs = c.ClickHoldMinMs + 1
	}
}

// NormalizeTypoRates ensures the conditional typo probabilities sum up to 1.
func (c *Config) NormalizeTypoRates() {
	total := c.TypoNeighborRate + c.TypoTransposeRate + c.TypoOmissionRate + c.TypoInsertionRate
	if total <= 1e-9 {
		if c.TypoRateMean > 0 || c.TypoRate > 0 {
			c.TypoNeighborRate = 0.25
			c.TypoTransposeRate = 0.25
			c.TypoOmissionRate = 0.25
			c.TypoInsertionRate = 0.25
		}
		return
	}
	c.TypoNeighborRate /= total
	c.TypoTransposeRate /= total
	c.TypoOmissionRate /= total
	c.TypoInsertionRate /= total
}